# Site settings
author: Alice Brunel
title: Alice's tech diary
header-img: img/home-bg.png
email: alc.brunel@gmail.com
copyright_name: Alice Brunel
description: > # this means to ignore newlines until "baseurl:"
  Journey towards web development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AliceBrunel

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-minimal